version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  # We forward this port because it's useful for debugging
      - "15672:15672" # Here, we can access RabbitMQ management plugin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=recon_user
      - POSTGRES_PASSWORD=recon_pass
      - POSTGRES_DB=recon_db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_backend
    command: ./entrypoint.sh
    volumes:
      - static_volume:/opt/ratiba/staticfiles
      - media_volume:/opt/ratiba/media
    ports:
      - 8001:8000
    environment:
      - DATABASE_NAME=recon_db
      - DATABASE_USER=recon_user
      - DATABASE_PASSWORD=recon_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SECRET_KEY=secret
      - PORT=8000
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

    depends_on:
     - db
     - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_backend
    environment:
      - DATABASE_NAME=recon_db
      - DATABASE_USER=recon_user
      - DATABASE_PASSWORD=recon_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SECRET_KEY=secret
      - PORT=8000
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - recon:/opt/recon
    command: celery -A src.celery worker --loglevel=DEBUG
    depends_on:
      - rabbitmq

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_backend
    environment:
      - DATABASE_NAME=recon_db
      - DATABASE_USER=recon_user
      - DATABASE_PASSWORD=recon_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SECRET_KEY=secret
      - PORT=8000
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - recon:/opt/recon
    command: celery -A src.celery beat --loglevel=DEBUG
    depends_on:
      - rabbitmq
      - worker

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
  rabbitmq_data:
  recon:
