version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=recon_user
      - POSTGRES_PASSWORD=recon_pass
      - POSTGRES_DB=recon_db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    command: ./entrypoint.sh
    volumes:
      - static_volume:/opt/recon/staticfiles
      - media_volume:/opt/recon/media
    ports:
      - 8000:8080
    environment:
      - DATABASE_NAME=recon_db
      - DATABASE_USER=recon_user
      - DATABASE_PASSWORD=recon_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SECRET_KEY=secret
      - PORT=8080
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*

    depends_on:
     - db

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
  recon:
