# Generated by Django 5.0.6 on 2024-09-21 19:56

import src.recon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSED", "Processed"),
                    ("SCHEDULED", "Scheduled"),
                    ("INPROGRESS", "Inprogress"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationresult",
            name="source_file",
            field=models.FileField(upload_to=src.recon.models.upload_to),
        ),
        migrations.AlterField(
            model_name="reconciliationresult",
            name="target_file",
            field=models.FileField(upload_to=src.recon.models.upload_to),
        ),
    ]
