# Generated by Django 5.0.6 on 2024-09-20 20:53

import django.utils.timezone
import src.common.models.attachment
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image/png", "PNG"),
                            ("image/jpeg", "JPEG"),
                            ("application/pdf", "PDF"),
                            ("application/vnd.ms-excel", "xlsx"),
                            ("application/msword", "doc"),
                            (
                                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                "docx",
                            ),
                            (
                                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                "xlsx",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        max_length=500, upload_to=src.common.models.attachment.upload_to
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "size",
                    models.IntegerField(
                        blank=True,
                        help_text="The size of the attachment in bytes",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
        ),
    ]
